server:
  port: 8010

spring:
  application:
    name: authorization

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/payment-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123