spring:
  application:
    name: transaction

  rabbitmq:
    addresses: guest:guest@${PAYMENT_QUEUE:localhost}

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:localhost}:${PAYMENT_DB_PORT:5432}/${PAYMENT_DB_NAME:payment-db}
    driver-class-name: org.postgresql.Driver
    username: ${PAYMENT_DB_USER:postgres}
    password: ${PAYMENT_DB_PASSWORD:123}

server:
  port: 8000

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /docs/specs

queue:
  notification:
    name: payment-notification-queue

services:
  authorization:
    uri: ${AUTHORIZATION_SERVICE_HOST:localhost}:${AUTHORIZATION_SERVICE_PORT:8010}
    endpoints:
      authorize-transaction: /authorize