server:
  port: 8000

spring:
  application:
    name: transaction

  rabbitmq:
    addresses: guest:guest@localhost

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/payment-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /docs/specs

queue:
  notification:
    name: payment-notification-queue

services:
  authorization:
    uri: http://localhost:8010
    endpoint: /authorize